import type { Metadata } from "next";
import "../../globals.css";
import { LayoutAuth } from "@/shared/ui/layout/LayoutAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Authayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LayoutAuth>{children}</LayoutAuth>;
}
